# Generated by Django 5.1.2 on 2025-01-22 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_ledger', '0018_transactionmodel_cleared_transactionmodel_reconciled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityModelProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'swappable': None,
                'indexes': [],
                'constraints': [],
            },
            bases=('django_ledger.entitymodel',),
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128, null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_django_ledger.entitymodelproxy', verbose_name='Category Entity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
